In [1]:
import pandas as pd
import numpy as np

In [33]:
chess=pd.read_csv("./projectfolder/Seyoung/Chessdata.csv",index_col=None,header=None)

C:\Users\PC\AppData\Local\Temp\ipykernel_29636\1918226354.py:1: DtypeWarning: Columns (262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367) have mixed types. Specify dtype option on import or set low_memory=False.
  chess=pd.read_csv("./projectfolder/Seyoung/Chessdata.csv",index_col=None,header=None)

In [34]:
chess

,0,1,2,3,4,5,6,7,8,9,...,358,359,360,361,362,363,364,365,366,367
0,e4,e5,Nf3,Nc6,Bb5,a6,Ba4,d6,c3,Bd7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,e4,e5,Nf3,Nc6,Bb5,a6,Ba4,Nf6,O-O,Be7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,d4,d5,c4,e6,Nf3,Nf6,Nc3,c6,e3,Nbd7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,c4,Nf6,Nf3,c6,Nc3,d5,e3,g6,d4,Bg7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nf3,Nf6,c4,b6,d3,g6,e4,d6,Nc3,Bg7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16024,d4,Nf6,Nf3,g6,g3,Bg7,Bg2,O-O,O-O,d6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16025,Nf3,d5,e3,Nf6,b3,Bf5,Be2,h6,Ba3,Nbd7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16026,d4,Nf6,c4,e6,Nc3,Bb4,e3,O-O,Bd2,d5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16027,d4,Nf6,c4,e6,Nc3,Bb4,e3,O-O,Bd3,d5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16028,e4,e5,Nf3,Nc6,d4,exd4,Nxd4,Bc5,Nb3,Bb6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
list1 = [x for x in range(0, 10)]

chess.columns
tot = chess[list1]
tot

         0    1    2    3    4     5     6    7    8     9
0       e4   e5  Nf3  Nc6  Bb5    a6   Ba4   d6   c3   Bd7
1       e4   e5  Nf3  Nc6  Bb5    a6   Ba4  Nf6  O-O   Be7
2       d4   d5   c4   e6  Nf3   Nf6   Nc3   c6   e3  Nbd7
3       c4  Nf6  Nf3   c6  Nc3    d5    e3   g6   d4   Bg7
4      Nf3  Nf6   c4   b6   d3    g6    e4   d6  Nc3   Bg7
...    ...  ...  ...  ...  ...   ...   ...  ...  ...   ...
16024   d4  Nf6  Nf3   g6   g3   Bg7   Bg2  O-O  O-O    d6
16025  Nf3   d5   e3  Nf6   b3   Bf5   Be2   h6  Ba3  Nbd7
16026   d4  Nf6   c4   e6  Nc3   Bb4    e3  O-O  Bd2    d5
16027   d4  Nf6   c4   e6  Nc3   Bb4    e3  O-O  Bd3    d5
16028   e4   e5  Nf3  Nc6   d4  exd4  Nxd4  Bc5  Nb3   Bb6

[16029 rows x 10 columns]

In [70]:
pd.DataFrame(tot)

         0    1    2    3    4     5     6    7    8     9
0       e4   e5  Nf3  Nc6  Bb5    a6   Ba4   d6   c3   Bd7
1       e4   e5  Nf3  Nc6  Bb5    a6   Ba4  Nf6  O-O   Be7
2       d4   d5   c4   e6  Nf3   Nf6   Nc3   c6   e3  Nbd7
3       c4  Nf6  Nf3   c6  Nc3    d5    e3   g6   d4   Bg7
4      Nf3  Nf6   c4   b6   d3    g6    e4   d6  Nc3   Bg7
...    ...  ...  ...  ...  ...   ...   ...  ...  ...   ...
16024   d4  Nf6  Nf3   g6   g3   Bg7   Bg2  O-O  O-O    d6
16025  Nf3   d5   e3  Nf6   b3   Bf5   Be2   h6  Ba3  Nbd7
16026   d4  Nf6   c4   e6  Nc3   Bb4    e3  O-O  Bd2    d5
16027   d4  Nf6   c4   e6  Nc3   Bb4    e3  O-O  Bd3    d5
16028   e4   e5  Nf3  Nc6   d4  exd4  Nxd4  Bc5  Nb3   Bb6

[16029 rows x 10 columns]

In [83]:
count= pd.DataFrame(tot).value_counts()

In [84]:
pd.DataFrame(count)

                                               0
0  1   2   3   4    5    6    7   8   9
e4 c5  Nf3 d6  d4   cxd4 Nxd4 Nf6 Nc3 a6     395
   e5  Nf3 Nc6 Bb5  a6   Ba4  Nf6 O-O Be7    233
   c5  Nf3 d6  d4   cxd4 Nxd4 Nf6 Nc3 Nc6     90
           Nc6 d4   cxd4 Nxd4 Nf6 Nc3 e5      87
           e6  d4   cxd4 Nxd4 Nc6 Nc3 Qc7     86
...                                          ...
d4 Nf6 c4  e5  dxe5 Ng4  Qd4  d6  Nc3 Nc6      1
                         Nf3  Nc6 Bf4 Bb4+     1
                         Bf4  g5  Bg3 Nc6      1
               d5   Bb4+ Bd2  Qe7 a3  Bxd2+    1
h4 d5  Nf3 Nf6 d4   e6   Bg5  c5  e3  Nc6      1

[7982 rows x 1 columns]

In [96]:
Freq= count[count>=5]

In [99]:
FreqDF=pd.DataFrame(Freq)

In [104]:
FreqDF.to_csv("Freq.csv",header=False)